[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_arcade = "A7kodx7FgCheVy4gXtnWMn2SLeEBSxtTjN86yKzFeHbx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./scripts/deploy-keys/deploy-wallet.json"

[scripts]
test = "pnpm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-game = "pnpm run init-game"
